// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Deliberately just DATABASE_URL, not a DIRECT_URL fallback: this file
    // loads on every CLI invocation, including the test suite's own
    // `tests/global-setup.ts`, which points DATABASE_URL at a throwaway
    // local Postgres it spins up itself before running `db push
    // --accept-data-loss` against it. A DIRECT_URL fallback here would have
    // silently overridden that and run a data-loss-accepting push against
    // the real Supabase database instead — caught in testing by Prisma's own
    // AI-agent safety guard, not by anything in this app. When pushing
    // schema changes against Supabase by hand, export DATABASE_URL=$DIRECT_URL
    // for that one command instead of changing this default.
    url: process.env["DATABASE_URL"],
  },
});
